services:
  - type: web
    name: evently-booking-system
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT  
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: evently-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: evently-redis
          property: connectionString
      # SendGrid Email Configuration
      - key: SENDGRID_API_KEY
        value: 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
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: apikey
      - key: SMTP_PASSWORD
        value: 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
      - key: SMTP_FROM
        value: Evently <nutalapatisrikrishna85@gmail.com>
  - type: redis
    name: evently-redis
    plan: free
    ipAllowList: []

databases:
  - name: evently-database
    databaseName: evently
    plan: free